### ISSUE TITLE
Crash on inserting a pattern that goes out of screen bounds.

### ISSUE THREAD

**Issue by Luke-Nukem** [Luke-Nukem/rs_life#3]
Also noticed that patterns break down when inserted near bottom edge.

Error below happens only when a pattern is inserted near right edge and it goes out of bounds. Can fix both issues with some bounds checking.

```
thread 'main' panicked at 'index out of bounds: the len is 145 but the index is 145', ../src/libcollections/vec.rs:1307
stack backtrace:
   1:     0x561d084e822f - std::sys::backtrace::tracing::imp::write::h6f1d53a70916b90d
   2:     0x561d084eb70d - std::panicking::default_hook::{{closure}}::h137e876f7d3b5850
   3:     0x561d084ea6ea - std::panicking::default_hook::h0ac3811ec7cee78c
   4:     0x561d084eac38 - std::panicking::rust_panic_with_hook::hc303199e04562edf
   5:     0x561d084eaad2 - std::panicking::begin_panic::h6ed03353807cf54d
   6:     0x561d084eaa10 - std::panicking::begin_panic_fmt::hc321cece241bb2f5
   7:     0x561d084ea991 - rust_begin_unwind
   8:     0x561d085259df - core::panicking::panic_fmt::h27224b181f9f037f
   9:     0x561d08525983 - core::panicking::panic_bounds_check::h19e9bbc59320a57e
  10:     0x561d08479865 - <collections::vec::Vec<T> as core::ops::Index<usize>>::index::hc0505a1b802ec602
                        at /buildslave/rust-buildbot/slave/stable-dist-rustc-linux/build/obj/../src/libcollections/vec.rs:1307
  11:     0x561d0848321e - game_of_life::grid::Grid::add_cell::hd9624ba563b58a61
                        at /home/luke/src/projects/rs_life/src/grid.rs:84
  12:     0x561d084833f1 - game_of_life::grid::Grid::add_pattern::hefde8eb5fc412afa
                        at /home/luke/src/projects/rs_life/src/grid.rs:89
  13:     0x561d08487ff9 - game_of_life::main::h9069cb1ec14730f2
                        at /home/luke/src/projects/rs_life/src/main.rs:113
  14:     0x561d084f31d6 - __rust_maybe_catch_panic
  15:     0x561d084e9f61 - std::rt::lang_start::h538f8960e7644c80
  16:     0x561d08490be3 - main
  17:     0x7f0110120290 - __libc_start_main
  18:     0x561d08411d99 - _start
                        at ../sysdeps/x86_64/start.S:120
  19:                0x0 - <unknown>
```

**Comment by Luke-Nukem** [comment]
Fixed.
